name: packlead
description: "Ordering tracking app"
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  permission_handler: ^11.0.1
  flutter_dotenv: ^5.1.0
  fl_chart: ^1.1.1
  http: ^1.2.2
  dio: ^5.9.1
  firebase_core: ^4.4.0
  firebase_database: ^12.1.2
  firebase_auth: ^6.3.0
  url_launcher: ^6.3.2
  intl: ^0.20.2
  dartz: ^0.10.1
  mocktail: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/packlead_logo.png